option('tests', type: 'feature', description: 'Build tests')
option(
    'phal_backend',
    type: 'combo',
    choices: ['legacy', 'next', 'none'],
    value: 'none',
    description: 'Select PHAL backend',
)
option(
    'attn_config',
    type: 'string',
    value: '',
    description: 'Attention handler default configuration override',
)
option(
    'op_dump_obj_path',
    type: 'string',
    value: '/org/openpower/dump',
    description: 'Object path requesting OpenPOWER dumps',
)
option(
    'transport-implementation',
    type: 'combo',
    choices: ['mctp-demux', 'af-mctp'],
    description: 'transport via af-mctp or mctp-demux',
)

option(
    'system_config',
    type: 'combo',
    choices: ['p10', 'p11', 'p12'],
    description: 'System configuration to build for',
)
